In [3]:
#pip install numpy

In [4]:
import numpy as np

In [7]:
array1 = np.array([43,45,76,86])
array2 = np.array([43,54,75,83])
array1 + array2

array([ 86,  99, 151, 169])

In [8]:
array3 = np.ones((2,3))
print(array3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
array4 = np.zeros((4,5))
print(array4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
array5 = np.eye(4)
print(array5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
array6 = np.arange(4,50,3)
print(array6)

[ 4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [13]:
array7 = np.arange(8,2000,8)
print(array7)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000 1008
 1016 1024 1032 1040 1048 1056 1064 1072 1080 1088 1096 1104 1112 1120
 1128 1136 1144 1152 1160 1168 1176 1184 1192 1200 1208 1216 1224 1232
 1240 1248 1256 1264 1272 1280 1288 1296 1304 1312 1320 1328 1336 1344
 1352 1360 1368 1376 1384 1392 1400 1408 1416 1424 1432 1440 1448 1456
 1464 1472 1480 1488 1496 1504 1512 1520 1528 1536 1544 1552 1560 1568
 1576 

In [23]:
np.ndim(array7)

1

In [24]:
#statistics

In [25]:
means = np.array([43,45,75,86,72])
average = np.mean(means)
print(average)

64.2


In [26]:
medians = np.median(means)
print(medians)

72.0


In [27]:
stds = np.std(means)
print(stds)

17.151093259614676


In [28]:
vari = np.var(means)
print(vari)

294.15999999999997


In [33]:
#Random

In [36]:
from numpy import random as rd

In [37]:
rad1 = rd.randint(100)
print(rad1)

53


In [38]:
rad2 = rd.randint(100,size = 10)
print(rad2)

[58 84 87 84 20 61 13 13 31 24]


In [39]:
rad3 = rd.randint(100,size = (4,5))
print(rad3)

[[28 45  5 98  6]
 [62 63 25 41  3]
 [31 21 98 38 88]
 [79 36 51 83 34]]


In [40]:
rand4 = rd.rand(10)
print(rand4)

[0.44708862 0.30639451 0.77601681 0.63721187 0.61633653 0.64383437
 0.55583521 0.4507979  0.8510106  0.68110481]


In [41]:
rand5 = 10*(rd.rand(10))
print(rand5)

[4.38779405 0.90209292 5.00890074 6.74402481 3.47114781 4.95746161
 8.38931967 3.94112776 4.21038249 4.49966515]


In [44]:
rd.seed(0)
sim = rd.randint(100, size = (4,5))
print(sim)

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]]


In [46]:
rd.seed(1)
sim1 = rd.randint(100, size = (4,5))
print(sim1)

[[37 12 72  9 75]
 [ 5 79 64 16  1]
 [76 71  6 25 50]
 [20 18 84 11 28]]


In [49]:
mer = np.hstack((sim,sim1))
print(mer)

[[44 47 64 67 67 37 12 72  9 75]
 [ 9 83 21 36 87  5 79 64 16  1]
 [70 88 88 12 58 76 71  6 25 50]
 [65 39 87 46 88 20 18 84 11 28]]


In [52]:
print(np.vstack((sim,sim1)))

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [37 12 72  9 75]
 [ 5 79 64 16  1]
 [76 71  6 25 50]
 [20 18 84 11 28]]


In [53]:
print(np.hstack((sim)))

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]


In [54]:
print(np.vstack((sim)))

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]]
