In [2]:
#opps
class myclass():
    val = 4
pay = myclass()
print(pay.val)

4


In [4]:
class person:
    def __init__ (self, name, age):
        self.name = name
        self.age = age
persons = person("Mark",44)
print(persons.name,persons.age)

Mark 44


In [14]:
#List
list = [3,4,5,6,7,4,5,6,7,8]
print(list[6:2:-1])

[5, 4, 7, 6]


In [20]:
#intialize an array
import numpy as np
are = np.array((1,2,3,5,6,7,7))
print(are)

[1 2 3 5 6 7 7]


In [26]:
import numpy
print(numpy.__version__)

2.0.0


In [27]:
#0-D array
import numpy as np
num  = np.array(432)
print(num)

432


In [28]:
#1-D array
import numpy as np
char = np.array([1,3,4,5,6,7])
print(char)

[1 3 4 5 6 7]


In [33]:
#3-D array
import numpy as np
numbers = np.array([[10,29,35,40],[35,75,36,79]])
print(numbers)

[[10 29 35 40]
 [35 75 36 79]]


In [31]:
#3-D array
import numpy as np
number = np.array([[1,2,3,4],[3,5,6,7],[5,6,7,8]])
print(number)

[[1 2 3 4]
 [3 5 6 7]
 [5 6 7 8]]


In [34]:
#numpy array slicing
import numpy as np
at = np.array([3,4,5,6,7,4])
print(at[2:6])
print(at[:6])
print(at[2:6:3])


[5 6 7 4]
[3 4 5 6 7 4]
[5 4]


In [35]:
#data type
import numpy as np
att = np.array(["q","r","d","k"])
nam = np.array((1,2,3,4,5,6),dtype = "S")
print(att.dtype)
print(nam)
print(nam.dtype)

<U1
[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [41]:
#copy of variables
import numpy as np
aat = np.array([[1,3,5,6],[5,6,7,8]])
dat = aat.copy()
dat[0,1] = 43
aat[1,3] = 66
print(dat)
print(aat)

[[ 1 43  5  6]
 [ 5  6  7  8]]
[[ 1  3  5  6]
 [ 5  6  7 66]]


In [42]:
# Find no.. of array and element
import numpy as np
data = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(data.shape)

(3, 4)


In [43]:
#Reshape
import numpy as np
date = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
reshape = date.reshape(3,4)
print(reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
#Iteration using for
import numpy as np
dat = np.array([2,3,4,5,6,7])
for bag in dat:
    print(bag)

2
3
4
5
6
7
